package com.podcastmodern.entity;
// Generated Nov 18, 2015 1:35:40 PM by Hibernate Tools 4.0.0

import javax.persistence.*;
import java.util.Date;

/**
 * ApplicationUser generated by hbm2java
 */
@Entity
@Table(name = "application_user", catalog = "podcastmodern")
public class ApplicationUser implements java.io.Serializable {

    private ApplicationUserId id;
    private User user;
    private Application application;
    private Date firstRegisterTime;

    public ApplicationUser() {
    }

    public ApplicationUser(ApplicationUserId id, User user, Application application) {
        this.id = id;
        this.user = user;
        this.application = application;
    }

    public ApplicationUser(ApplicationUserId id, User user, Application application, Date firstRegisterTime) {
        this.id = id;
        this.user = user;
        this.application = application;
        this.firstRegisterTime = firstRegisterTime;
    }

    @EmbeddedId

    @AttributeOverrides({@AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false)),
        @AttributeOverride(name = "applicationId", column = @Column(name = "application_id", nullable = false))})
    public ApplicationUserId getId() {
        return this.id;
    }

    public void setId(ApplicationUserId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "application_id", nullable = false, insertable = false, updatable = false)
    public Application getApplication() {
        return this.application;
    }

    public void setApplication(Application application) {
        this.application = application;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "first_register_time", length = 19)
    public Date getFirstRegisterTime() {
        return this.firstRegisterTime;
    }

    public void setFirstRegisterTime(Date firstRegisterTime) {
        this.firstRegisterTime = firstRegisterTime;
    }

}
