package com.podcastmodern.entity;
// Generated Nov 18, 2015 12:40:38 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ApplicationPodcastId generated by hbm2java
 */
@Embeddable
public class ApplicationPodcastId implements java.io.Serializable {

	private int applicationId;
	private int podcastId;

	public ApplicationPodcastId() {
	}

	public ApplicationPodcastId(int applicationId, int podcastId) {
		this.applicationId = applicationId;
		this.podcastId = podcastId;
	}

	@Column(name = "application_id", nullable = false)
	public int getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(int applicationId) {
		this.applicationId = applicationId;
	}

	@Column(name = "podcast_id", nullable = false)
	public int getPodcastId() {
		return this.podcastId;
	}

	public void setPodcastId(int podcastId) {
		this.podcastId = podcastId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ApplicationPodcastId))
			return false;
		ApplicationPodcastId castOther = (ApplicationPodcastId) other;

		return (this.getApplicationId() == castOther.getApplicationId())
				&& (this.getPodcastId() == castOther.getPodcastId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getApplicationId();
		result = 37 * result + this.getPodcastId();
		return result;
	}

}
