package com.podcastmodern.entity;
// Generated Oct 20, 2015 2:32:43 PM by Hibernate Tools 4.0.0

import org.hibernate.annotations.SQLDelete;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import java.util.Date;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Customer generated by hbm2java
 */
@Entity(name = "customer")
@SQLDelete(sql = "UPDATE customer SET is_active = false WHERE customer_id = ?")
@Table(name = "customer", catalog = "podcastmodern")
public class Customer implements java.io.Serializable {

    private Integer customerId;
    private String name;
    private String surname;
    private Date birthdate;
    private String email;
    private String isActive;
    private String userName;
    private String password;

    public Customer() {
    }

    public Customer(String name, String surname, Date birthdate, String email, String isActive, Set orders,
                    Set addresses) {
        this.name = name;
        this.surname = surname;
        this.birthdate = birthdate;
        this.email = email;
        this.isActive = isActive;

    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "customer_id", unique = true, nullable = false)
    public Integer getCustomerId() {
        return this.customerId;
    }

    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    @Column(name = "name", length = 45)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "surname", length = 45)
    public String getSurname() {
        return this.surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "birthdate", length = 19)
    public Date getBirthdate() {
        return this.birthdate;
    }

    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }

    @Column(name = "email", length = 100)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "is_active", length = 45)
    public String getIsActive() {
        return this.isActive;
    }

    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }

    @Column(name = "user_name", length = 45)
    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    @Column(name = "password", length = 45)
    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }


}
