package com.podcastmodern.entity;
// Generated Nov 18, 2015 1:35:40 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Podcast generated by hbm2java
 */
@Entity
@Table(name = "podcast", catalog = "podcastmodern")
public class Podcast implements java.io.Serializable {

	private Integer podcastId;
	private String itunesUrl;
	private String otherRssUrl;
	private String description;
	private Integer currentItemCount;
	private String publisher;
	private Boolean isPublic;
	private Date lastItemDate;
	private String imageurl;
	private String author;
	private String name;
	

	public Podcast() {
	}

	public Podcast(String itunesUrl, String otherRssUrl, String description, Integer currentItemCount, String publisher,
			Boolean isPublic, Date lastItemDate, String imageurl, String author, String name) {
		this.itunesUrl = itunesUrl;
		this.otherRssUrl = otherRssUrl;
		this.description = description;
		this.currentItemCount = currentItemCount;
		this.publisher = publisher;
		this.isPublic = isPublic;
		this.lastItemDate = lastItemDate;
		this.imageurl = imageurl;
		this.author = author;
		this.name = name;
		
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "podcast_id", unique = true, nullable = false)
	public Integer getPodcastId() {
		return this.podcastId;
	}

	public void setPodcastId(Integer podcastId) {
		this.podcastId = podcastId;
	}

	@Column(name = "itunes_url", length = 250)
	public String getItunesUrl() {
		return this.itunesUrl;
	}

	public void setItunesUrl(String itunesUrl) {
		this.itunesUrl = itunesUrl;
	}

	@Column(name = "other_rss_url", length = 250)
	public String getOtherRssUrl() {
		return this.otherRssUrl;
	}

	public void setOtherRssUrl(String otherRssUrl) {
		this.otherRssUrl = otherRssUrl;
	}

	@Column(name = "description", length = 400)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "current_item_count")
	public Integer getCurrentItemCount() {
		return this.currentItemCount;
	}

	public void setCurrentItemCount(Integer currentItemCount) {
		this.currentItemCount = currentItemCount;
	}

	@Column(name = "publisher", length = 20)
	public String getPublisher() {
		return this.publisher;
	}

	public void setPublisher(String publisher) {
		this.publisher = publisher;
	}

	@Column(name = "is_public")
	public Boolean getIsPublic() {
		return this.isPublic;
	}

	public void setIsPublic(Boolean isPublic) {
		this.isPublic = isPublic;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_item_date", length = 19)
	public Date getLastItemDate() {
		return this.lastItemDate;
	}

	public void setLastItemDate(Date lastItemDate) {
		this.lastItemDate = lastItemDate;
	}

	@Column(name = "imageurl", length = 250)
	public String getImageurl() {
		return this.imageurl;
	}

	public void setImageurl(String imageurl) {
		this.imageurl = imageurl;
	}

	@Column(name = "author", length = 50)
	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	

}
